project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

commit_message: 'chore(i18n): sync translations'

preserve_hierarchy: true
files:
  - source: assets/i18n/en_US.json
    translation: assets/i18n/%locale_with_underscore%.json